"""Build the Claude-handoff prompt for the doc scaffold feature."""
from __future__ import annotations
from pathlib import Path
from datetime import datetime, timezone

from ..config import CATALOG_DIR, Target


HEADER = """# nekoclaude doc scaffold

You are being invoked to scaffold project documentation. The user picked the
following document types via the nekoclaude UI. Read the codebase enough to
write each file correctly (don't just fill in a template — actually study the
project), then write each file to the repo root.

Each section below is the prompt for one doc type. After all sections, write
the files. Do not write a meta summary at the end.

"""


def write_prompt(target: Target, kinds: list[str]) -> Path:
    parts: list[str] = [HEADER]
    base = CATALOG_DIR / "doc-prompts"
    for k in kinds:
        p = base / f"{k}.prompt.md"
        if p.is_file():
            parts.append(f"\n---\n## {k}.md\n\n" + p.read_text())
        else:
            parts.append(f"\n---\n## {k}.md\n\n(no prompt file found at {p})")
    parts.append(
        f"\n---\nGenerated by nekoclaude at "
        f"{datetime.now(timezone.utc).isoformat()} for target {target.label}\n"
    )
    dest = target.claude_dir / ".nekoclaude-handoff-prompt.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("".join(parts))
    return dest
